In [ ]:
# Import necessary libraries
from sklearn.decomposition import PCA, FastICA, TruncatedSVD, KernelPCA, FactorAnalysis
from sklearn.manifold import TSNE, LocallyLinearEmbedding, Isomap, MDS
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.cross_decomposition import CCA
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.covariance import EmpiricalCovariance, ShrunkCovariance, EllipticEnvelope
from sklearn.datasets import load_iris
import numpy as np

# Load a sample dataset (Iris dataset for demonstration)
X, y = load_iris(return_X_y=True)

# 1. Principal Component Analysis (PCA)
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

# 2. Independent Component Analysis (ICA)
ica = FastICA(n_components=2, random_state=0)
X_ica = ica.fit_transform(X)

# 3. Singular Value Decomposition (SVD)
svd = TruncatedSVD(n_components=2)
X_svd = svd.fit_transform(X)

# 4. Factor Analysis
fa = FactorAnalysis(n_components=2)
X_fa = fa.fit_transform(X)

# 5. Kernel PCA
kpca = KernelPCA(n_components=2, kernel='rbf')
X_kpca = kpca.fit_transform(X)

# 6. t-distributed Stochastic Neighbor Embedding (t-SNE)
tsne = TSNE(n_components=2, random_state=0)
X_tsne = tsne.fit_transform(X)

# 7. Locally Linear Embedding (LLE)
lle = LocallyLinearEmbedding(n_components=2, random_state=0)
X_lle = lle.fit_transform(X)

# 8. Isomap with increased number of neighbors
isomap = Isomap(n_components=2, n_neighbors=10)  # Increase the number of neighbors
X_isomap = isomap.fit_transform(X)

# 9. Multidimensional Scaling (MDS)
mds = MDS(n_components=2, random_state=0)
X_mds = mds.fit_transform(X)

# 10. Linear Discriminant Analysis (LDA) for Dimensionality Reduction
lda = LinearDiscriminantAnalysis(n_components=2)
X_lda = lda.fit_transform(X, y)  # Requires y (target labels)

# 11. Canonical Correlation Analysis (CCA)
cca = CCA(n_components=1)
X_cca = cca.fit_transform(X, y.reshape(-1, 1))  # Reshape y to make it 2D


# 12. Spearman and Pearson Correlation Coefficients
# Spearman is usually computed using scipy, while Pearson can be done with numpy
from scipy.stats import spearmanr, pearsonr
corr_pearson, _ = pearsonr(X[:, 0], X[:, 1])  # Example between two features
corr_spearman, _ = spearmanr(X[:, 0], X[:, 1])  # Example between two features

# 13. Explained Variance (as part of PCA)
explained_variance = pca.explained_variance_ratio_

# 14. Covariance Estimation
cov_estimator = EmpiricalCovariance().fit(X)
cov_matrix = cov_estimator.covariance_

# 15. Shrunk Covariance
shrunk_cov = ShrunkCovariance().fit(X)
shrunk_cov_matrix = shrunk_cov.covariance_

# 16. Elliptic Envelope (Robust Covariance Estimation)
elliptic_env = EllipticEnvelope(contamination=0.1).fit(X)
outliers = elliptic_env.predict(X)

# Output results of the first few methods for demonstration
print("PCA Components:\n", X_pca[:5])
print("ICA Components:\n", X_ica[:5])
print("SVD Components:\n", X_svd[:5])
print("Spearman Correlation:", corr_spearman)
print("Pearson Correlation:", corr_pearson)

/usr/local/lib/python3.10/dist-packages/sklearn/manifold/_isomap.py:383: UserWarning: The number of connected components of the neighbors graph is 2 > 1. Completing the graph to fit Isomap might be slow. Increase the number of neighbors to avoid this issue.
  self._fit_transform(X)
/usr/local/lib/python3.10/dist-packages/scipy/sparse/_index.py:108: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])


PCA Components:
 [[-2.68412563  0.31939725]
 [-2.71414169 -0.17700123]
 [-2.88899057 -0.14494943]
 [-2.74534286 -0.31829898]
 [-2.72871654  0.32675451]]
ICA Components:
 [[-1.37275281  0.50407976]
 [-1.27723374 -0.50255829]
 [-1.36915115 -0.44695282]
 [-1.26103444 -0.79029728]
 [-1.39601297  0.51660691]]
SVD Components:
 [[ 5.91274714 -2.30203322]
 [ 5.57248242 -1.97182599]
 [ 5.44697714 -2.09520636]
 [ 5.43645948 -1.87038151]
 [ 5.87564494 -2.32829018]]
Spearman Correlation: -0.166777658283235
Pearson Correlation: -0.11756978413300206
